config/routes.rb
Blogger::Application.routes.draw do
 	root to: "articles#index"
 	resources :articles do
 		resources :comments
	end
	resources :tags
end


	

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings
	has_attached_file :image
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }

	#attr_accessible :image
	#attr_accessible :title, :body, :tag_list, :image


	def tag_list
		self.tags.collect do |tag|
			tag.name
		end.join(", ")
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  		self.tags = new_or_found_tags
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
	end

	def show
		@articles = Article.find(params[:id])
		@comment = Comment.new 
		@comment.article_id = @articles.id
	end

	def new
		@articles = Article.new
	end

	def create
		@articles = Article.new(params[:tag])

		flash.notice = "Article '#{@articles.title}' Created "

		redirect_to article_path(@article)
	end

	def destroy
		@articles = Article.find(params[:id])
		@articles.destroy

		flash.notice = "Article '#{@articles.title}' Deleted"

		redirect_to articles_path
	end

	def edit
		@articles = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :body, :tag_list)
	end

	def update
		@articles = Article.find(params[:id])
		@articles.update(article_params)

		flash.notice = "Article '#{@articles.title}' Updated"

		redirect_to articles_path(@articles)
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@articles, html: {multipart: true}) do |f| %>
  <ul>
  <% @articles.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :image, "Attach an Image" %><br />
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <p>
   <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
<% end %>

<p>
  <% if @article.image.exists? %>
      <%= image_tag @article.image.url %><br/>
  <% end %>
  <%= f.label :image, "Attach a New Image" %><br />
  <%= f.file_field :image %>
</p>




app/views/articles/edit.html.erb
<h1> Editing an Article<h1>

<%= render partial: 'form' %>

app/views/articles/index.erb
<h1>All Articles</h1>

<ul id="articles">
	<% @articles.each do |article| %>
	<li><%= link_to article.title, article_path(article), :class =>"article_title" %></li>
	<% end %>
</ul>

<%= link_to "Create a New Article", new_article_path, :class => "new_article" %>


app/views/articles/new.html.erb
<h1>Creating a new Article</h1>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @articles.title %></h1>
<p>
  Tags:
  <% @articles.tags.each do |tag| %>
    <%= link_to tag.name, tags_path %>
  <% end %>
</p>

<p><%= image_tag @article.image.url %></p>

<p> <%= @articles.body %></p>

<%= render partial: 'comments/form' %>

<%= link_to "<< Go Back to Article List", articles_path %>
<%= link_to "delete", article_path(@article), 
:method => :delete,
:confirm => "Are you sure?" %>

<%= link_to "<<Edit Article", edit_article_path(@article) %>

<h3> Comments (<%= @articles.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @articles.comments %>

<p>
  <% if @articles.image.exists? %>
      <%= image_tag @articles.image.url %><br/>
  <% end %>
  <%= f.label :image, "Attach a New Image" %><br />
  <%= f.file_field :image %>
</p>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="flash"><%= flash.notice %></p> 
<%= yield %>

</body>
</html>